# Debug mode: Generate single .env file at project root for local testing

locals {
  # Build JSON structure for all resources
  debug_runtimes = merge(
    {
      for name, config in var.runtimes : name => {
        id           = awscc_bedrockagentcore_runtime.runtime_code[name].agent_runtime_id
        arn          = awscc_bedrockagentcore_runtime.runtime_code[name].agent_runtime_arn
        version      = awscc_bedrockagentcore_runtime.runtime_code[name].agent_runtime_version
        endpoint_id  = try(awscc_bedrockagentcore_runtime_endpoint.runtime[name].id, null)
        endpoint_arn = try(awscc_bedrockagentcore_runtime_endpoint.runtime[name].agent_runtime_endpoint_arn, null)
        env_vars     = config.environment_variables
      }
      if config.source_type == "CODE"
    },
    {
      for name, config in var.runtimes : name => {
        id           = awscc_bedrockagentcore_runtime.runtime_container[name].agent_runtime_id
        arn          = awscc_bedrockagentcore_runtime.runtime_container[name].agent_runtime_arn
        version      = awscc_bedrockagentcore_runtime.runtime_container[name].agent_runtime_version
        endpoint_id  = try(awscc_bedrockagentcore_runtime_endpoint.runtime[name].id, null)
        endpoint_arn = try(awscc_bedrockagentcore_runtime_endpoint.runtime[name].agent_runtime_endpoint_arn, null)
        env_vars     = config.environment_variables
      }
      if config.source_type == "CONTAINER"
    }
  )

  debug_memories = {
    for name, config in var.memories : name => {
      id  = awscc_bedrockagentcore_memory.memory[name].id
      arn = awscc_bedrockagentcore_memory.memory[name].memory_arn
    }
  }

  debug_gateways = {
    for name, config in var.gateways : name => {
      id  = awscc_bedrockagentcore_gateway.gateway[name].id
      arn = awscc_bedrockagentcore_gateway.gateway[name].gateway_arn
      url = awscc_bedrockagentcore_gateway.gateway[name].gateway_url
    }
  }

  debug_browsers = {
    for name, config in var.browsers : name => {
      id  = awscc_bedrockagentcore_browser_custom.browser[name].id
      arn = awscc_bedrockagentcore_browser_custom.browser[name].browser_arn
    }
  }

  debug_code_interpreters = {
    for name, config in var.code_interpreters : name => {
      id  = awscc_bedrockagentcore_code_interpreter_custom.code_interpreter[name].id
      arn = awscc_bedrockagentcore_code_interpreter_custom.code_interpreter[name].code_interpreter_arn
    }
  }

  debug_gateway_targets = {
    for name, config in var.gateway_targets : name => {
      target_id = aws_bedrockagentcore_gateway_target.gateway_target[name].target_id
      name      = aws_bedrockagentcore_gateway_target.gateway_target[name].name
    }
  }

  debug_ecr_repositories = {
    for name, config in var.runtimes : name => aws_ecr_repository.runtime[name].repository_url
    if config.source_type == "CONTAINER" && config.container_source_path != null
  }
}

resource "local_file" "debug_env" {
  count = var.debug ? 1 : 0

  filename = "${path.root}/autogen/.env"
  content = join("\n", concat(
    ["# Auto-generated by Terraform - DO NOT COMMIT"],
    ["# Add .env to your .gitignore"],
    [""],
    ["# AWS Context"],
    ["AWS_REGION=${data.aws_region.current.id}"],
    ["AWS_ACCOUNT_ID=${data.aws_caller_identity.current.account_id}"],
    [""],
    ["# All Resources (JSON nested structure)"],
    length(local.debug_runtimes) > 0 ? ["RUNTIMES='${jsonencode(local.debug_runtimes)}'"] : [],
    length(local.debug_memories) > 0 ? ["MEMORIES='${jsonencode(local.debug_memories)}'"] : [],
    length(local.debug_gateways) > 0 ? ["GATEWAYS='${jsonencode(local.debug_gateways)}'"] : [],
    length(local.debug_browsers) > 0 ? ["BROWSERS='${jsonencode(local.debug_browsers)}'"] : [],
    length(local.debug_code_interpreters) > 0 ? ["CODE_INTERPRETERS='${jsonencode(local.debug_code_interpreters)}'"] : [],
    length(local.debug_gateway_targets) > 0 ? ["GATEWAY_TARGETS='${jsonencode(local.debug_gateway_targets)}'"] : [],
    [""],
    ["# S3/ECR Resources"],
    length(aws_s3_bucket.runtime) > 0 ? ["S3_BUCKETS='${jsonencode({for k, v in aws_s3_bucket.runtime : k => v.id})}'"] : [],
    length(local.debug_ecr_repositories) > 0 ? ["ECR_REPOSITORIES='${jsonencode(local.debug_ecr_repositories)}'"] : [],
    [""]
  ))

  file_permission = "0600"
}

# Generate test scripts for each runtime
resource "local_file" "test_runtime_script" {
  for_each = var.debug ? var.runtimes : {}

  filename = "${path.root}/autogen/test_${each.key}.sh"
  content  = <<-EOT
    #!/bin/bash
    # Auto-generated test script for runtime: ${each.key}
    # Usage: ./test_${each.key}.sh "Your test message"

    RUNTIME_ID="${try(
      awscc_bedrockagentcore_runtime.runtime_code[each.key].agent_runtime_id,
      awscc_bedrockagentcore_runtime.runtime_container[each.key].agent_runtime_id
    )}"
    INPUT_TEXT="$${1:-Hello from test script}"

    echo "Testing runtime: ${each.key}"
    echo "Runtime ID: $RUNTIME_ID"
    echo "Input: $INPUT_TEXT"
    echo ""

    aws bedrock-agent-runtime invoke-agent \
      --agent-runtime-id "$RUNTIME_ID" \
      --input-text "$INPUT_TEXT" \
      --region ${data.aws_region.current.id} \
      --output json
  EOT

  file_permission = "0755"
}
